### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by vaaakoo** [vaaakoo/DevJobs#1]
## to-do list

- [x]   Make a custom theme for your project.
- [x]  Tailwinds testing and styling.
- [x]  Make a custom module with controller.
- [x]  Configuration of the project and checking everything.
